apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-sample-service
namePrefix: prod-
resources:
  - ../../base
  - pdb.yaml
  - hpa.yaml
patches:
  - path: replica-patch.yaml
  - path: resources-patch.yaml
images:
  - name: ghcr.io/org/sample-service
    newTag: 1.0.0             # prod pins to an immutable, signed semver tag ONLY
configMapGenerator:
  - name: sample-service-config
    literals:
      - LOG_LEVEL=warn
      - ENVIRONMENT=production
