controller:
  replicaCount: 3
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true       # scraped by Prometheus
  service:
    type: LoadBalancer
  config:
    use-forwarded-headers: "true"
    ssl-redirect: "true"
podDisruptionBudget:
  enabled: true
  minAvailable: 2
